### ISSUE TITLE
[main] product list 마크업하기

### ISSUE THREAD

**Issue by hayeonn2** [hayeonn2/TIL#3]
## 🌳 작업 브랜치
project-js

## 📋 TASK 개요
product list 마크업을 진행합니다.

## ✅ To Do 및 진행상황
- [x] main 상단 탭메뉴 마크업 하기
- [x] main product list 마크업 하기
- [x] main product list css 완성하기
